import {
  CoffeeRoast,
  CoffeeRecipe,
  Syrup,
  Variations,
  Milk,
} from "./CoffeeRecipe";

export const CoffeeData: CoffeeRecipe[] = [
  {
    title: "Iced Americano",
    variations: Variations.Americano,
    ingredients: [CoffeeRoast.Light, Syrup.Syrup, "cold water", "ice"],
    steps: [
      "Add(pour) (4)oz of cold water to the cup.",
      "Add syrup(10ml for normal) and mix them well.",
      "Make ready the roasted coffee",
      "Mix the roasted coffee to the water slowly",
      "Fill the cup with ice, let it overflow a little bit.",
    ],
  },
  {
    title: "Hot Americano",
    variations: Variations.Americano,
    ingredients: [CoffeeRoast.Light, Syrup.Syrup, "hot water"],
    steps: [
      "Add(pour) (4)oz of hot water to the disposable cup.",
      "Add syrup(10ml for normal) and mix them well.",
      "Make ready the roasted coffee",
      "Mix the espresso to the water slowly",
    ],
  },
  {
    title: "Coconut Americano",
    variations: Variations.Americano,
    ingredients: [CoffeeRoast.Medium, Syrup.Syrup, "Coconut liquid", "ice"],
    steps: [
      "Add(pour) (5)oz of coconut liquid to the cup.",
      "Add syrup(10ml for normal) and mix them well.",
      "Fill the cup with ice, let it overflow a little bit.",
      "Make ready the roasted coffee",
      "Finally, pour the espresso onto the ice",
    ],
  },
  {
    title: "Orange Americano",
    variations: Variations.Americano,
    ingredients: [CoffeeRoast.Light, Syrup.Syrup, "Orange juice", "ice"],
    steps: [
      "Add(pour) (4)oz of orange juice to the cup.",
      "Add syrup(10ml for normal) and mix them well.",
      "Fill the cup with ice, let it overflow a little bit.",
      "Make ready the roasted coffee",
      "Finally, pour the espresso onto the ice",
    ],
  },
  {
    title: "Honey Americano",
    variations: Variations.Americano,
    ingredients: [CoffeeRoast.Light, Syrup.Syrup, "Honey", "Hot water", "ice"],
    steps: [
      "Take (3)oz of hot water to the mag.",
      "Add honey(10ml for normal) and mix them well.",
      "Fill the cup with ice, let it overflow a little bit.",
      "Make ready the roasted coffee",
      "Finally, pour the espresso onto the ice",
    ],
  },
  {
    title: "Hazelnut Americano",
    variations: Variations.Americano,
    ingredients: [
      CoffeeRoast.Medium,
      Syrup.Halzelnut,
      "Sugar liquid",
      "Water",
      "ice",
    ],
    steps: [
      "Take (3)oz of hot water to the mag.",
      "Add honey(10ml for normal) and mix them well.",
      "Fill the cup with ice, let it overflow a little bit.",
      "Make ready the roasted coffee",
      "Finally, pour the espresso onto the ice",
    ],
  },
  {
    title: "Es-Yen",
    variations: Variations.Latte,
    ingredients: [
      CoffeeRoast.Medium,
      Syrup.Syrup,
      Milk.Condense,
      Milk.Jued,
      "ice",
    ],
    steps: [
      "Add(pour) (1)oz of condensed milk to the cup.",
      "Add syrup according to the sweetness level. For normal, we use it for 10ml",
      "Stir well, and then fill the cup with ice.",
      "Make the roasted coffee ready.",
      "Pour the espresso onto the ice.",
      "Make sure the ice a little bit overflow.",
    ],
  },
  {
    title: "Iced Latte(Brazil Santos Beans)",
    variations: Variations.Latte,
    ingredients: [CoffeeRoast.Medium, Syrup.Syrup, "fresh milk", "ice"],
    steps: [
      "Add(pour) (4)oz of fresh milk to the cup.",
      "Add syrup according to the sweetness level. For normal, we use it for 10ml",
      "Stir well, and then fill the cup with ice.",
      "Make the roasted coffee ready.",
      "Pour the espresso onto the ice.",
      "Make sure the ice a little bit overflow.",
    ],
  },
  {
    title: "Vanilla Latte(Brazil Santos Beans)",
    variations: Variations.Latte,
    ingredients: [CoffeeRoast.Medium, Syrup.Vanilla, "fresh milk", "ice"],
    steps: [
      "Add(pour) (4)oz of fresh milk to the cup.",
      "Add vanilla syrup according to the sweetness level. For normal, we use it for 20ml.",
      "Stir well, and then fill the cup with ice.",
      "Make the roasted coffee ready.",
      "Pour the espresso onto the ice.",
      "Make sure the ice a little bit overflow.",
      "Finally, put a thin layer of milk foam at the top",
    ],
  },
  {
    title: "Hazelnut Latte(Brazil Santos Beans)",
    variations: Variations.Latte,
    ingredients: [CoffeeRoast.Medium, Syrup.Halzelnut, "fresh milk", "ice"],
    steps: [
      "Add(pour) (4)oz of fresh milk to the cup.",
      "Add hazelnut syrup according to the sweetness level. For normal, we use it for 20ml.",
      "Stir well, and then fill the cup with ice.",
      "Make the roasted coffee ready.",
      "Pour the espresso onto the ice.",
      "Make sure the ice a little bit overflow.",
      "Finally, put a thin layer of milk foam at the top",
    ],
  },
  {
    title: "Mint Latte(Brazil Santos Beans)",
    variations: Variations.Latte,
    ingredients: [CoffeeRoast.Medium, Syrup.Mint, "fresh milk", "ice"],
    steps: [
      "Add(pour) (4)oz of fresh milk to the cup.",
      "Add mint syrup according to the sweetness level. For normal, we use it for 20ml.",
      "Stir well, and then fill the cup with ice.",
      "Make the roasted coffee ready.",
      "Pour the espresso onto the ice.",
      "Make sure the ice a little bit overflow.",
      "Finally, put a thin layer of milk foam at the top",
    ],
  },

  {
    title: "Strawberry Latte(Brazil Santos Beans)",
    variations: Variations.Latte,
    ingredients: [
      CoffeeRoast.Medium,
      Syrup.Syrup,
      "Strawberry juice",
      "fresh milk",
      "ice",
    ],
    steps: [
      "Take (3)oz of strawberry juce.",
      "Puor it into the cup in till shape and fill the cup with ice",
      "Take (4)oz of fresh milk",
      "Add syrup according to the sweetness level. For normal, we use it for 10ml.",
      "Stir well, and then fill the cup with ice.",
      "Make the roasted coffee ready.",
      "Pour the espresso onto the ice.",
      "Make sure the ice a little bit overflow.",
    ],
  },
  {
    title: "Coconut Latte(Brazil Santos Beans)",
    variations: Variations.Latte,
    ingredients: [
      CoffeeRoast.Light,
      Syrup.Syrup,
      "Coconut liquid",
      "Condense milk",
      "Nomjued",
      "fresh milk",
      "ice",
    ],
    steps: [
      "Add(pour) (4)oz of cocount liquid to the cup.",
      "Add condense milk and Nomduced according to the sweetness level. For normal, we use (1)oz of condense milk and (1) of Nomjued.",
      "Stir well, and then fill the cup with ice.",
      "Make the roasted coffee ready.",
      "Pour the espresso onto the ice.",
      "Make sure the ice a little bit overflow.",
    ],
  },
  {
    title: "Hojicha Latte",
    variations: Variations.Latte,
    ingredients: [
      CoffeeRoast.Light,
      Syrup.Syrup,
      "fresh milk",
      "hot water",
      "ice",
    ],
    steps: [
      "Add (160)ml of fresh milk into the cup. ",
      "Add syrup according to the sweetness level and stir well.",
      "Fill the cup with ice",
      "Pour (2)oz of hot water into the porcelain cup.",
      "Add (4.5)g of hojicha powder onto the hot water and mix them with the machine.",
      "Pour the mixture onto the ice",
      "Add some hojicha powder on the top.",
    ],
  },
  {
    title: "Nutella Mocca",
    variations: Variations.Latte,
    ingredients: [
      CoffeeRoast.Light,
      Syrup.Syrup,
      "nutella paste",
      "fresh milk",
      "coconut powder",
      "milk foam",
    ],
    steps: [
      "Put the nutella paste on the internal surface of the cup for decoration.",
      "Add (4)oz of fresh milk in to the cup.",
      "Add syrup according to the sweetness level and stir well.",
      "And the fill the cup with ice.",
      "Make ready the roasted coffee.",
      "Mix roasted coffee, 15g of nutella and about 1g of coconut powder.",
      "Pour the mixture onto the ice.",
      "Add milk foam on the top.",
      "Add some coconut powder on the top of it.",
    ],
  },
  {
    title: "Mocoa",
    variations: Variations.Latte,
    ingredients: [
      CoffeeRoast.Light,
      Syrup.Syrup,
      "chocolate topping",
      "fresh milk",
      "mocoa powder",
      "coconut powder",
      "milk foam",
    ],
    steps: [
      "Top chocolate topping on the internal surface of the cup for decoration purpose.",
      "Pour (4)oz of fresh milk into the cup.",
      "Add syrup according to the sweetness level and stir well.",
      "Fill the cup with ice",
      "Add (---)g of Mocoa powder with the filter into the porcelain cup.",
      "Add (1)g of coconut powder onto the mocoa powder.",
      "Pour (200)ml of [cold/hot] water onto the mixed powder and stir well.",
      "And then pour the mixture onto the ice.",
      "Add milk foam on the top.",
      "Add some coconut powder on the top of it.",
    ],
  },
  {
    title: "Hojicha Latte",
    variations: Variations.Latte,
    ingredients: [
      CoffeeRoast.Light,
      Syrup.Syrup,
      "fresh milk",
      "hot water",
      "ice",
    ],
    steps: [
      "Add (160)ml of fresh milk into the cup. ",
      "Add syrup according to the sweetness level and stir well.",
      "Fill the cup with ice",
      "Pour (2)oz of hot water into the porcelain cup.",
      "Add (4.5)g of hojicha powder onto the hot water and mix them with the machine.",
      "Pour the mixture onto the ice",
      "Add some hojicha powder on the top.",
    ],
  },
  // { title: "", ingredients: [CoffeeRoast.Light, Syrup], steps: [] },
];
